//! OBTENER TODOS LOS GAMES
export const GET_ALL_VIDEOGAMES = "GET_ALL_VIDEOGAMES";
//! OBTENER GAMES POR NOMBRE
export const GET_VIDEOGAME_BY_NAME = "GET_VIDEOGAME_BY_NAME";
//! OBTENER LOS DETALLES DEL JUEGO CUANDO LO CLICKEEN
export const GET_GAME_DETAILS = "GET_GAME_DETAILS";
//! FILTROS POR ORIGEN Y POR GENEROS
export const FILTER_BY_ORIGIN = "FILTER_BY_ORIGIN";
export const FILTER_BY_GENRES = "FILTER_BY_GENRES";
//! ORDENAMIENTO ASCENDENTE Y DESENDENTE POR NOMBRE O RATING
export const ORDER_BY_RATING = "ORDER_ASC_BY_RATING";
export const ORDER_BY_NAME = "ORDER_ASC_BY_NAME";
//! SIEMPRE QUE SE MONTE EL COMPONENTE FORMULARIO DISPACHAR GET_GENRES
export const GET_GENRES = "GET_GENRES";
//! CREAR JUEGO POR FOMULARIO
export const POST_VIDEOGAME = "POST_VIDEOGAME";
