//! OBTENER TODOS LOS GAMES
export const GET_ALL_VIDEOGAMES = "GET_ALL_VIDEOGAMES";
//! OBTENER GAMES POR NOMBRE
export const GET_VIDEOGAME_BY_NAME = "GET_VIDEOGAME_BY_NAME";
//! OBTENER LOS DETALLES DEL JUEGO CUANDO LO CLICKEEN
export const GET_GAME_DETAILS = "GET_GAME_DETAILS";
//! SIEMPRE QUE SE MONTE EL COMPONENTE FORMULARIO DISPACHAR GET_GENRES
export const GET_GENRES = "GET_GENRES";
//! CREAR JUEGO POR FOMULARIO
export const POST_VIDEOGAME = "POST_VIDEOGAME";
//! RESET FILTRES ESTA ATENTO A CUANDO DESELECCIONES UN FILTRO PARA VOLVER A MOSTRAR LOS FILTRADOS
export const FILTER = "FILTER";
export const ERROR_SERVER = "ERROR_SERVER";
